/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StravaRouteImport } from './routes/_strava'
import { Route as StravaIndexRouteImport } from './routes/_strava.index'
import { Route as StravaWorkoutRouteImport } from './routes/_strava.workout'
import { Route as StravaWorkoutIdRouteImport } from './routes/_strava.workout.$id'

const StravaRoute = StravaRouteImport.update({
  id: '/_strava',
  getParentRoute: () => rootRouteImport,
} as any)
const StravaIndexRoute = StravaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StravaRoute,
} as any)
const StravaWorkoutRoute = StravaWorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => StravaRoute,
} as any)
const StravaWorkoutIdRoute = StravaWorkoutIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StravaWorkoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof StravaIndexRoute
  '/workout': typeof StravaWorkoutRouteWithChildren
  '/workout/$id': typeof StravaWorkoutIdRoute
}
export interface FileRoutesByTo {
  '/workout': typeof StravaWorkoutRouteWithChildren
  '/': typeof StravaIndexRoute
  '/workout/$id': typeof StravaWorkoutIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_strava': typeof StravaRouteWithChildren
  '/_strava/workout': typeof StravaWorkoutRouteWithChildren
  '/_strava/': typeof StravaIndexRoute
  '/_strava/workout/$id': typeof StravaWorkoutIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/workout' | '/workout/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/workout' | '/' | '/workout/$id'
  id:
    | '__root__'
    | '/_strava'
    | '/_strava/workout'
    | '/_strava/'
    | '/_strava/workout/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StravaRoute: typeof StravaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_strava': {
      id: '/_strava'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StravaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_strava/': {
      id: '/_strava/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StravaIndexRouteImport
      parentRoute: typeof StravaRoute
    }
    '/_strava/workout': {
      id: '/_strava/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof StravaWorkoutRouteImport
      parentRoute: typeof StravaRoute
    }
    '/_strava/workout/$id': {
      id: '/_strava/workout/$id'
      path: '/$id'
      fullPath: '/workout/$id'
      preLoaderRoute: typeof StravaWorkoutIdRouteImport
      parentRoute: typeof StravaWorkoutRoute
    }
  }
}

interface StravaWorkoutRouteChildren {
  StravaWorkoutIdRoute: typeof StravaWorkoutIdRoute
}

const StravaWorkoutRouteChildren: StravaWorkoutRouteChildren = {
  StravaWorkoutIdRoute: StravaWorkoutIdRoute,
}

const StravaWorkoutRouteWithChildren = StravaWorkoutRoute._addFileChildren(
  StravaWorkoutRouteChildren,
)

interface StravaRouteChildren {
  StravaWorkoutRoute: typeof StravaWorkoutRouteWithChildren
  StravaIndexRoute: typeof StravaIndexRoute
}

const StravaRouteChildren: StravaRouteChildren = {
  StravaWorkoutRoute: StravaWorkoutRouteWithChildren,
  StravaIndexRoute: StravaIndexRoute,
}

const StravaRouteWithChildren =
  StravaRoute._addFileChildren(StravaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  StravaRoute: StravaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
